In [10]:
import torch
torch.manual_seed(7)
torch.__version__, torch.cuda.is_available()

('1.1.0', False)

`_` means inplace

https://www.udacity.com/course/deep-learning-pytorch--ud188

https://github.com/udacity/deep-learning-v2-pytorch/tree/master/intro-to-pytorch

# Tensors

## Linear Alegra

In [29]:
features = torch.randn((1,5)) #tensor of size (1,5)
weights = torch.randn_like(features)
bias = torch.randn((1,1))
print(features,weights,bias)

tensor([[0.1328, 0.1373, 0.2405, 1.3955, 1.3470]]) tensor([[2.4382, 0.2028, 2.4505, 2.0256, 1.7792]]) tensor([[-0.9179]])


In [23]:
# matrix multiplication must have (ncols from 1st = nrows from 2nd)
print(torch.mm(features,weights.transpose(0,1)))  #args are dimenions to swap
print(torch.mm(features,weights.reshape(5,1))) #args are new nrow,ncol
print(torch.mm(features,weights.resize_(5,1))) #args are new nrow,ncol; if different numel, remove or add (uninitialized)
print(torch.mm(features,weights.view(5,1))) #.view returns new tensor

tensor([[-1.9796]])
tensor([[-1.9796]])
tensor([[-1.9796]])
tensor([[-1.9796]])


## Functions

In [24]:
1/(1 + torch.exp(torch.sum(features * weights) + bias))

tensor([[0.9552]])

## To/from Numpy

memory is shared

In [27]:
import numpy as np
a = np.random.rand(2,2)
b = torch.from_numpy(a)
print(b)
print(b.numpy())

tensor([[0.2744, 0.6924],
        [0.9054, 0.0106]], dtype=torch.float64)
[[0.2743871  0.69241128]
 [0.90539865 0.01060206]]


In [28]:
b.mul_(2) # inplace multiplicatino
a # shows that memory is shared

array([[0.54877421, 1.38482256],
       [1.8107973 , 0.02120412]])

# Datasets